```{r global_options, message = FALSE}
library(knitr) # enables knit output formatting
  opts_chunk$set(fig.align="center", fig.height=4, fig.width=8) # format knit output
library(tidyverse)
library(patchwork)
library(fs)
library(data.table)
```

```{r message = FALSE}
theme_set(theme_bw(base_size = 12))
pal1 <- c("#E64B35", "#3578E6", "#00A087", "#5A35E3", "#3C5488",
          "#353540", "#F39B7F", "#4DBBD5", "#91D1C2", "#E6A435")

pal2 <- c("#5A35E3", "#B435E3", "#3578E6", "#73787C", "#FDE725", 
          "#4BD2AC", "#00A201")
```

# Data analyses for space aptamers
**April 2024**

------

This document contains research notes and code generated by:

> **Rachael M. Cox**  
> Biochemistry PhD
> University of Texas at Austin  
> rachaelcox@utexas.edu  

------

## Functions

```{r combine_data}
combine_data <- function(files, fdr_cutoff, write_out=NULL, out_prefix=NULL){
  
  dfs <- list()
  for (k in seq.int(5, 15, 1)){
    
    idx <- grep(paste0('_', k, 'mers_'), files)
    print(paste0('Reading data: ', files[idx]))
    df <- read_csv(files[idx]) %>%
      mutate(kmer_size = k)
    
    bg_cols <- grep('^bg_\\d*', names(df), value = TRUE)
    zero_cols <- grep('^0w_\\d*', names(df), value = TRUE)
    one_cols <- grep('^1w_\\d*', names(df), value = TRUE)
    three_cols <- grep('^3w_\\d*', names(df), value = TRUE)
    
    df <- df %>%
      mutate(bg_mean_count = rowMeans(select(., bg_cols)),
             `0w_mean_count` = rowMeans(select(., zero_cols)),
             `1w_mean_count` = rowMeans(select(., one_cols)),
             `3w_mean_count` = rowMeans(select(., three_cols)),
             ) %>%
      select(-matches('^bg_\\d$'), -matches('^0w_\\d$'),
             -matches('^1w_\\d$'), -matches('^3w_\\d$'), -confect)
    
    df <- df %>%
      filter(fdr <= fdr_cutoff)
    
    if(!missing(write_out)){
      print('Writing out data for consensus sequence step ...')
      outname = paste0(out_prefix, '_', k, 'mers_weights.csv')
      df %>%
        select(edge, `3w`) %>%
        rename(weight = `3w`) %>%
        arrange(desc(weight)) %>% 
        data.table::fwrite(outname)
    }
    
    dfs[[k]] <- df
    
    }
    
  print('Combining data ...')
  data <- reduce(dfs, rbind)
  print('Done!')
  return(data)
}
```

```{r slice_all_k}
slice_all_k <- function(df, top_n, filter="", k_list){
  
  sliced <- df %>%
    filter(label != filter,
           kmer_size %in% k_list) %>%
    group_by(kmer_size) %>% 
    slice_max(order_by = `3w`, n = as.numeric(top_n)) %>% 
    mutate(p = strsplit(edge, "")) %>% 
    unnest_wider(p, names_sep = "_") %>%
    mutate_each(funs(chartr("ATCG","1234",.))) %>%
    select(edge, avg_expr, fdr, `0w`, `3w`, kmer_size, exp, label,
           matches("^p_\\d*"), matches("*mean*")) %>%
    ungroup()
  
  make_numeric <- sliced %>% select(matches("^p_\\d*"), matches("*mean*")) %>% colnames()
  sliced <- sliced %>% mutate_at(vars(make_numeric), as.numeric)
  sliced[is.na(sliced)] <- 0
  
  return(sliced)
}
```

------

## Data processing

### Read in & combine data

```{r}
# get file names
wd='/stor/work/Marcotte/project/rmcox/'
strep_files <- dir(paste0(wd, 'oligos/results/streptavidin/labeled_nolib'), 
                   pattern='*all_washes_enriched_nolib_labeled.csv', full.names=TRUE)
oligo_1_files <- dir(paste0(wd, 'oligos/results/oligo_1/labeled_nolib'), 
                     pattern='*all_washes_enriched_nolib_labeled.csv', full.names=TRUE)
oligo_2_files <- dir(paste0(wd, 'oligos/results/oligo_2/labeled_nolib'), 
                     pattern='*all_washes_enriched_nolib_labeled.csv', full.names=TRUE)
oligo_3_files <- dir(paste0(wd, 'oligos/results/oligo_3/labeled_nolib'), 
                     pattern='*all_washes_enriched_nolib_labeled.csv', full.names=TRUE)
oligo_b_files <- dir(paste0(wd, 'oligos/results/oligo_b/labeled_nolib'), 
                     pattern='*all_washes_enriched_nolib_labeled.csv', full.names=TRUE)
```

```{r}
# read in & combine data
cutoff = 0.10

strep_data <- combine_data(strep_files, fdr_cutoff = cutoff, write_out = TRUE, 
                           out_prefix = paste0(wd, 'oligos/results/streptavidin/consensus_seqs_nolib/streptavidin')) %>%
  mutate(exp = "streptavidin")

oligo_1_data <- combine_data(oligo_1_files, fdr_cutoff = cutoff, write_out = TRUE, 
                             out_prefix = paste0(wd, 'oligos/results/oligo_1/consensus_seqs_nolib/oligo_1')) %>%
  mutate(label = case_when(edge %in% strep_data$edge ~ 'streptavidin bound',
                           label == 'no match' ~ 'everything else',
                           TRUE ~ label)) %>%
  mutate(exp = "oligo 1")
oligo_2_data <- combine_data(oligo_2_files, fdr_cutoff = cutoff, write_out = TRUE, 
                             out_prefix = paste0(wd, 'oligos/results/oligo_2/consensus_seqs_nolib/oligo_2')) %>%
  mutate(label = case_when(edge %in% strep_data$edge ~ 'streptavidin bound',
                           label == 'no match' ~ 'everything else',
                           TRUE ~ label)) %>%
  mutate(exp = "oligo 2")
oligo_3_data <- combine_data(oligo_3_files, fdr_cutoff = cutoff, write_out = TRUE, 
                             out_prefix = paste0(wd, 'oligos/results/oligo_3/consensus_seqs_nolib/oligo_3')) %>%
  mutate(label = case_when(edge %in% strep_data$edge ~ 'streptavidin bound',
                           label == 'no match' ~ 'everything else',
                           TRUE ~ label)) %>%
  mutate(exp = "oligo 3")
oligo_b_data <- combine_data(oligo_b_files, fdr_cutoff = cutoff, write_out = TRUE, 
                             out_prefix = paste0(wd, 'oligos/results/oligo_b/consensus_seqs_nolib/oligo_b')) %>%
  mutate(label = case_when(edge %in% strep_data$edge ~ 'streptavidin bound',
                           label == 'no match' ~ 'everything else',
                           TRUE ~ label)) %>%
  mutate(exp = "oligo b")
```

### Get top k-mers for each experiment

```{r}
top_n = 25
k_list = c(11,13,15)
strep_slice <- slice_all_k(strep_data, top_n, 
                           filter="", k_list)
oligo_1_slice <- slice_all_k(oligo_1_data, top_n, 
                             filter="streptavidin bound", k_list)
oligo_2_slice <- slice_all_k(oligo_2_data, top_n, 
                             filter="streptavidin bound", k_list)
oligo_3_slice <- slice_all_k(oligo_3_data, top_n, 
                             filter="streptavidin bound", k_list)
oligo_b_slice <- slice_all_k(oligo_b_data, top_n, 
                             filter="streptavidin bound", k_list)

all_data <- rbind(oligo_1_slice, oligo_2_slice,
                      oligo_3_slice, strep_slice) 
```


### Add consensus sequence dats

```{r}
# new code for consensus sequence data
```


### Run PCA

```{r}
all_data_pca <- all_data %>%
  select(-edge, -label, -kmer_size, -exp) %>% 
  mutate_if(is.character, as.numeric) %>%
  scale() %>%
  prcomp()

# add exp information back into pca data
pca_labeled <- data.frame(all_data_pca$x, 
                          edge = all_data$edge, 
                          label = all_data$label,
                          exp = all_data$exp)
```

------

## Figures

### K-mer counts

```{r}
oligo_1_data %>%
  ggplot(aes(x = as.factor(kmer_size), fill = label)) +
  geom_bar(position = position_dodge2(width = 1, preserve = "single")) +
  scale_y_log10() +
  scale_fill_manual(values=pal1) +
  labs(title = "oligo 1")

oligo_2_data %>%
  ggplot(aes(x = as.factor(kmer_size), fill = label)) +
  geom_bar(position = position_dodge2(width = 1, preserve = "single")) +
  scale_y_log10() +
  scale_fill_manual(values=pal1) +
  labs(title = "oligo 2")

oligo_3_data %>%
  ggplot(aes(x = as.factor(kmer_size), fill = label)) +
  geom_bar(position = position_dodge2(width = 1, preserve = "single")) +
  scale_y_log10() +
  scale_fill_manual(values=pal1) +
  labs(title = "oligo 3")

oligo_b_data %>%
  ggplot(aes(x = as.factor(kmer_size), fill = label)) +
  geom_bar(position = position_dodge2(width = 1, preserve = "single")) +
  scale_y_log10() +
  scale_fill_manual(values=pal1) +
  labs(title = "oligo b")

strep_data %>%
  ggplot(aes(x = as.factor(kmer_size), fill = label)) +
  geom_bar(position = position_dodge2(width = 1, preserve = "single")) +
  scale_y_log10() +
  scale_fill_manual(values=pal1) +
  labs(title = "streptavidin")
```

### K-mer fold change

```{r}
# plot log2fc for each label for each k
oligo_1_data %>%
  ggplot(aes(x = as.factor(kmer_size), y = `3w`, fill = label)) +
  geom_boxplot() +
  scale_fill_manual(values=pal1)

oligo_2_data %>%
  ggplot(aes(x = as.factor(kmer_size), y = `3w`, fill = label)) +
  geom_boxplot() +
  scale_fill_manual(values=pal1)

oligo_3_data %>%
  ggplot(aes(x = as.factor(kmer_size), y = `3w`, fill = label)) +
  geom_boxplot() +
  scale_fill_manual(values=pal1)

oligo_b_data %>%
  ggplot(., aes(x = as.factor(kmer_size), y = `3w`, fill = label)) +
  geom_boxplot() +
  scale_fill_manual(values=pal1)
```

### K-mer overlap

How many k-mers are unique to each substrate? 
```{r}
# Venn diagrams
library(ggVennDiagram)
k = 15
oligo_1_k_subset <- oligo_1_data %>% filter(kmer_size == k)
oligo_2_k_subset <- oligo_2_data %>% filter(kmer_size == k)
oligo_3_k_subset <- oligo_3_data %>% filter(kmer_size == k)
strep_k_subset <- strep_data %>% filter(kmer_size == k)

x <- list(oligo_1 = oligo_1_k_subset$edge, 
          oligo_2 = oligo_2_k_subset$edge, 
          oligo_3 = oligo_3_k_subset$edge, 
          streptavidin = strep_k_subset$edge)

ggVennDiagram(x, color = "black", lwd = 0.8, lty = 1, 
              label = "count") +
  scale_fill_viridis_c(direction = -1, option = "B")

ggVennDiagram(x[1:3], color = "black", lwd = 0.8, lty = 1, 
              label = "count") +
  scale_fill_viridis_c(direction = -1, option = "A")
```

### PCA plots

```{r}
# plot PC1 and PC2
pca_labeled %>%
  ggplot(., aes(x = PC1, y = PC2, color = exp)) +
  geom_point(size = 4, alpha = 0.5) +
  scale_color_manual(values = pal1) +
  theme(legend.position = "top",
        legend.title = element_blank())

percent <- 100*all_data_pca$sdev^2 / sum(all_data_pca$sdev^2)
perc_data <- data.frame(percent = percent, PC = 1:length(percent))
ggplot(perc_data, aes(x = PC, y = percent)) + 
  geom_col() +
  ylab("% variance explained")
```

```{r}
# plot rotation matrix
library(ggrepel)

# capture the rotation matrix in a data frame
rotation_data <- data.frame(
  all_data_pca$rotation, 
  variable = row.names(all_data_pca$rotation))

# define an arrow style
arrow_style <- arrow(
  length = unit(0.05, "inches"),
  type = "closed")

# now plot, using geom_segment() for arrows and ggrepel() for labels
ggplot(rotation_data) + 
  geom_segment(aes(xend = PC1, yend = PC2), 
               x = 0, y = 0, arrow = arrow_style) + 
  geom_text_repel(aes(x = PC1, y = PC2, label = variable),
                  color = "#3C5488",
                  nudge_x = 0.1,
                  segment.size = 0, max.overlaps = 100) + 
  xlim(-1., 1.25) + 
  ylim(-1., 1.) +
  coord_fixed() # fix aspect ratio to 1:1
```

------

## Archived code

### Debugging

```{r echo = TRUE, results = 'hide'}
# Code generated from debugging
```

### Failed strategies

```{r echo = TRUE, results = 'hide'}
# Code and/or pipelines that didn't work & why
```

