---
title: "speed_test_analysis"
author: "Rachael M. Cox"
output: html_document
---

Speedtests
```{r}


 df_edge_count %>% select(Node2) %>%
    unique %>%
   separate_rows(Node2, sep = "||") -> tmp


actin <- read_csv("/project/rmcox/deBruijn_graphs/speed_tests/dBg_output/COG5277_dBg_7mers.csv")

df <- actin %>%
      filter(ProteinID != "ProteinID")

hasXs <- df %>% mutate(hasX = case_when(grepl("X", Node1)~ 1)) %>% filter(hasX == 1) %>%
  group_by(ProteinID) %>% 
     summarize(totX = sum(hasX, na.rm = TRUE)) %>%
     arrange(totX)


df_prot_order <- df %>% select(ProteinID) %>%
         filter(!ProteinID %in% hasXs$ProteinID) %>%
         unique %>%
         rowid_to_column(var = "order") 

    
# somewhere between row 50 and 70

# This is alignable and doable
prot_sel <- df_prot_order %>% head(200)

    
df_edge_count  <- df %>%
       filter(ProteinID %in% prot_sel$ProteinID) %>%
       select(Node1, Node2) %>%
       count(Node1, Node2) %>% arrange(desc(n))

df_unique_edges <- df_edge_count %>%
      select(Node1, Node2) %>%
      unique()

frame1 <- df_unique_edges %>% 
   # mutate(ProteinID = "") %>%
    #mutate(order = 0) %>%
    #mutate(walked_edge = FALSE) %>%
    left_join(df_edge_count, by = c("Node1", "Node2"))
    #filter(Node1 != "GSILAS" & Node2 != "SILASL")
    #filter(n < 13)
    #select(-step) 


gr_frame1 <- frame1 %>% as_tbl_graph()

p_layout <- ggraph(gr_frame1, 'kk') + 
  geom_edge_link0(aes(alpha = n))


p_layout 

p_layout %>% ggsave(filename = "/stor/work/Marcotte/project/cmcwhite/data/debruijn/COG5277_dBg_7mers_200seqs.png", device = "png", dpi = 600, height = 8, width = 8, units = "in")
p_layout %>% ggsave(filename = "/stor/work/Marcotte/project/cmcwhite/data/debruijn/COG5277_dBg_7mers_200seqs.pdf", device = "pdf", dpi = 600, height =8, width = 8, units = "in")



#restofframes <- df %>% https://marccomp01.ccbb.utexas.edu/rstudio/graphics/plot_zoom_png?width=1920&height=1040
#    inner_join(df_prot_order, by = "ProteinID") %>%
#    filter(ProteinID %in%  prot_sel$ProteinID) %>%
#    mutate(walked_edge = TRUE) %>%
#    left_join(df_edge_count, by = c("Node1", "Node2"))

allframes <- bind_rows(frame1, restofframes)


gr <- allframes %>% 
  tidygraph::as_tbl_graph() %>%
  activate("nodes") %>% 
  mutate(step = row_number()) %>%
  mutate(label = case_when(step == max(step) ~ "C", step == min(step) ~ "N")) 




```



```{r}


exp_details <- read_csv("exp_details.csv", col_names = c("family", "num_seqs")) 

setwd('/project/rmcox/deBruijn_graphs/speed_tests/benchmark_fastas/')
files = dir(pattern = "*_lengths.txt") # get file names


lengths <- data_frame(filename = files) %>% # create a data frame
                                         # holding the file names
  mutate(file_contents = map(filename,          # read files into
           ~ read_tsv(.))) %>%  # a new data column
  unnest()





setwd("/project/rmcox/deBruijn_graphs/speed_tests/results")
files <- dir(pattern = "*_results.csv") # get file names

custom_read_csv <- function(file){
  a <- read_csv(file, col_names = c("family", "algorithm","raw_time"), col_types = cols(raw_time = col_character()))
  print(a)
  return(a)
  
}

times <- files %>%
  map(custom_read_csv) %>%    # read in all the files individually, using
  reduce(rbind)        # reduce with rbind into one dataframe



median_lengths <- lengths %>%
  group_by(filename) %>%
  summarize(
    median_length = median(ProteinLength)
  ) %>%
  mutate(family = str_replace(filename, "_lengths.txt", "")) 




#times %>%


times_formatted <- times %>%
    complete(family, algorithm) %>%
    filter(!(algorithm == "UPP" & is.na(raw_time))) %>%
    mutate(raw_time = case_when(is.na(raw_time) ~ '36:00:00',
                                TRUE ~ raw_time) )%>%
    mutate(dt = case_when(
                          grepl("[.]", raw_time)  ~ lubridate::ms(raw_time),  # check warning message
                          TRUE ~ lubridate::hms(raw_time))) %>%
    mutate(seconds = lubridate::period_to_seconds(dt)) %>%
    mutate(minutes = seconds/60) %>%
  
   left_join(exp_details, by = "family") %>%
  left_join(median_lengths, by = "family") 

  

          
ordering <- c("deBruijn",  "clustalo", "mafft",  "UPP",  "KALIGN", "MUSCLE" )

times_formatted  %>%
  ggplot(aes(x = num_seqs, y = median_length))+ 
     geom_point()

# THIS plot
times_formatted %>%

  ggplot(aes(x = fct_relevel(algorithm, ordering), y = minutes, group = family, color = num_seqs)) +
  geom_point() + 
  geom_line() +
  scale_color_viridis() +
  geom_hline(yintercept = 2160, linetype = "dashed") +
  NULL
 # scale_y_log10()


# Inset this plot
times_formatted %>%
  filter(algorithm %in% c("deBruijn",  "clustalo", "mafft")) %>% 

  ggplot(aes(x = fct_relevel(algorithm, ordering), y =  minutes, group = family, color = num_seqs)) +
  geom_point() + 
  geom_line() +
  scale_color_viridis()




times_formatted %>%
    ggplot(aes(x  = num_seqs, y = minutes, group = algorithm, color = algorithm)) +
  geom_line() +
  facet_wrap(~algorithm, scales = "free_y")


a <- read_csv("dBg_results.csv", col_names = FALSE, col_types = cols(X3 = col_character()))
a %>% mutate(b = lubridate::ms(X3))  






  
  rename(dataset = X1) %>%
  rename(algorithm = X2) %>%
  rename(time = X3)

```

sel_complete <- times_formatted %>% filter(algorithm == "KALIGN")

times_formatted %>% filter(!family %in% sel_complete$family) %>% select(family) %>% unique %>% write_csv("KALIGN_DNF.txt")


```{r}





function (x, y = NULL)) 
{
     ncy <- ncx <- ncol(x)
            if (ncx == 0) 
                stop("'x' is empty")
            r <- matrix(0, nrow = ncx, ncol = ncy)
            for (i in seq_len(ncx)) {
                for (j in seq_len(i)) {
                  x2 <- x[, i]
                  y2 <- x[, j]
                  ok <- complete.cases(x2, y2)
                  x2 <- rank(x2[ok])
                  y2 <- rank(y2[ok])
                  r[i, j] <- if (any(ok)) 
                    .Call(C_cor, x2, y2, 1L, method == "kendall")
                  else NA
                }
            }
            r <- r + t(r) - diag(diag(r))
            rownames(r) <- colnames(x)
            colnames(r) <- colnames(x)
            r
        }
    }
```


```{r}

get_overlap <- function(x, y){
  # x and y are vectors
  return(sum(x == y, na.rm = TRUE))

}


overlapfxn <- function(mat){

    ncx =  ncol(mat)

    print(ncx)
    r <- matrix(0, nrow = ncx, ncol = ncx)

    for(x in seq(0, ncx)){
      for(y in seq(0, ncx)){

          r[x,y] = get_overlap(mat[,x], mat[,y])
      }
    }
    
    rownames(r) <- colnames(mat)
    colnames(r) <- colnames(mat)
    return(r)
}



calc_distance <- function(df){
  
  
 print(unique(df$fam))
 kmer_wide <- df %>%
 select(-fam) %>%
 mutate(edge = paste(Node1, Node2, sep = '-')) %>% 
 select(-Node1, -Node2) %>%
 mutate(presence = 1) %>%
  unique %>%
 spread(ProteinID,  presence)


  kmer_wide_mat <- as.matrix(select(kmer_wide, -edge) )

   
  distance_mat <- overlapfxn(kmer_wide_mat) 
  print(distance_mat)
  
  overlap_tidy <- distance_mat %>% as.data.frame %>%
  rownames_to_column(var = 'Protein1') %>%
  gather(Protein2, overlap, -Protein1) %>%
  as_tibble() %>%
  filter(Protein1 != Protein2) 

  return(overlap_tidy)

}



totlengthfxn <- function(mat){
  
    ncx =  ncol(mat)

    print(ncx)
    r <- matrix(0, nrow = ncx, ncol = ncx)

    for(x in seq(0, ncx)){
      for(y in seq(0, ncx)){

          r[x,y] = sum(mat[,x], mat[,y])
      }
    }
    
    rownames(r) <- colnames(mat)
    colnames(r) <- colnames(mat)
    return(r)
}


#Longest_common_subsequence().
calc_totlength <- function(df){
    nkmers <- df %>% 
       group_by(ProteinID) %>% 
       count() %>% ungroup()

    nkmer_mat <- nkmers %>% spread(ProteinID, n) %>% as.matrix()

   
    nkmer_totlength_mat <- totlengthfxn(nkmer_mat) 
 
    totlength_tidy <- nkmer_totlength_mat %>% as.data.frame %>%
    rownames_to_column(var = 'Protein1') %>%
    gather(Protein2, totlength, -Protein1) %>%
    as_tibble() %>%
    filter(Protein1 != Protein2) 
    return(totlength_tidy)
}




df_wholedataset <- read_csv("/project/cmcwhite/data/debruijn/swisstree_debruijns/STall_6mer.csv") %>%
  filter(ProteinID != "ProteinID") %>%
  mutate(Node1 = toupper(Node1)) %>%
  mutate(Node2 = toupper(Node2))

overlap_total <- df_wholedataset %>% 
  mutate(fam = str_extract(ProteinID, "^.....")) %>%
          #filter(fam %in% c("ST001")) %>%
           split(.$fam) %>%
           map_df(., calc_distance )

totlength_total <- df_wholedataset %>% 
  mutate(fam = str_extract(ProteinID, "^.....")) %>%
          #filter(fam %in% c("ST001")) %>%
           split(.$fam) %>%
           map_df(., calc_totlength )


totals_combined <- overlap_total %>% left_join(totlength_total, by = c("Protein1", "Protein2")) %>%
  mutate(fam = str_extract(Protein1, "^.....")) %>%
   mutate(totlengthcorrected = overlap / totlength) %>% 
  group_by(fam) %>%
  arrange(desc(overlap)) %>%
    rowid_to_column(var = "overlap_rank") %>%
   arrange(desc(totlengthcorrected)) %>%
    rowid_to_column(var = "totlengthcorrected_rank")
         
  
totals_combined %>%
  ggplot(aes(x = overlap_rank, totlengthcorrected_rank)) +
  geom_point() + 
  facet_wrap(~fam) 

 
totals_combined %>%
  ggplot(aes(x = overlap, totlengthcorrected)) +
  geom_point() + 
  facet_wrap(~fam)


#overlap_tidy_final <- overlap_total %>%
#  mutate(fam = str_extract(Protein1, "^.....")) %>%
#  
#  ungroup 



totals_combined   %>%
  group_by(fam) %>%
  mutate(inverted_overlap = max(overlap) - overlap) %>%
    ungroup() %>%
  select(Protein1, Protein2, inverted_overlap) %>%
  write_delim("inverted_overlap_STall.tsv", col_names = FALSE, delim = "\t")


totals_combined   %>%
  group_by(fam) %>%
  mutate(recip_overlap = 1/overlap) %>%
    ungroup() %>%
  select(Protein1, Protein2, recip_overlap) %>%
  write_delim("recip_overlap_STall.tsv", col_names = FALSE, delim = "\t")




totals_combined   %>%
  group_by(fam) %>%
  mutate(inverted_overlap_totlengthcorrected = max(totlengthcorrected) - totlengthcorrected) %>%
  mutate(recip_overlap_totlengthcorrected = 1/totlengthcorrected) %>%
  ungroup() %>%
  #ggplot(aes(x = recip_overlap_totlengthcorrected,y = inverted_overlap_totlengthcorrected  )) + geom_point() + facet_wrap(~fam)
  ggplot(aes(x = inverted_overlap_totlengthcorrected)) + geom_density()
  
  select(Protein1, Protein2, inverted_overlap_totlengthcorrected ) %>%
  write_delim("inverted_overlap_totlengthcorrected_STall.tsv", col_names = FALSE, delim = "\t")



```

```{r}


overlap_tidy 

kmer_wide %>% select(ST001_016, ST001_001) %>% 
  rowwise() %>%
  mutate(x = sum(ST001_016, ST001_001, na.rm= TRUE)) %>%
  arrange(desc(x))



ST001_016 <- df %>% filter(ProteinID == "ST001_016")
ST001_001 <- df %>% filter(ProteinID == "ST001_001")
ST001_016 %>% inner_join(ST001_001, by = c("Node1", "Node2"))
```


test lgl 
```{r}
frame1  %>%
  select(Node1, Node2) %>%
  unique %>%
  filter(Node1 != Node2) %>%
  mutate(FirstNode = pmin(Node1, Node2), SecondNode = pmax(Node1, Node2)) %>%
  select(-Node1, -Node2) %>%
  rename(Node1 = FirstNode, Node2 = SecondNode) %>%
  unique %>%
  write_delim("lgls/SF001_6.ncol", delim = " ",col_names = FALSE)


p_layout <- ggraph(gr_frame1, 'lgl') + 
  geom_edge_link0()
p_layout


```


```{r}
dat <- tibble(x=rnorm(100), y=rnorm(100), time=1:100) 
dat %>% 
  ggplot()  + 
  geom_point(aes(x=x, y=y)) +
  geom_point(aes(x=x, y=y), shape=4, size=10) +
  transition_time(time) + 
  shadow_mark(exclude_layer=0)


palette_OkabeIto_black <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")
colorblocks <- c("#FF0000","#0072B2","#E69F00","#009E24", "#979797","#5530AA", "#111111")
colors_key <- c("Red", "Blue", "Orange","Green",  "Grey", "Purple","Black") 
palette <- rep(colorblocks, 20)

```

