---
title: "test_dbg_graphs"
output: html_document
date: "2023-03-03"
---

```{r}
library(knitr) # enables knit output formatting
  opts_chunk$set(fig.align="center", fig.height=3, fig.width=4) # format knit output
library(tidyverse) # contains ggplot2, dplyr, tidyr, readr, stringr, etc
  theme_set(theme_bw(base_size = 12)) # set default plot theme for ggplot2
library(ggrepel) # enables dynamic plot labeling
library(ggthemes) # enables colorblind-friendly color palette
library(scales) # imports function show_col() for displaying color palettes
library(janitor) # imports function clean_names() for auto-formatting bad column names

library(tidygraph)
library(ggraph)  

palette_pretty <- c("#009E24", "#0072B2","#E69F00", "#FF0000", "#979797", "#5530AA", "#1E1E1E")
setwd("/stor/work/Marcotte/project/rmcox/deBruijn_graphs/petase/")

# reproducibility seed
set.seed(13)
```

```{r}
dbg <- read_csv("../pu_degradases/results/urethane_dBg_6mers_unique.csv") %>%
  select(Node1, Node2, ProteinCount) %>%
  mutate(edges = paste0(Node1, Node2))

dbg_test <- head(dbg, 1000)
```

```{r}
# create tidygraph object
tg <- as_tbl_graph(dbg, directed = TRUE)
```

```{r}
# plot graph using ggraph
p <- ggraph(tg, layout = "kk") + 
  geom_edge_link(aes(color = ProteinCount, width = ProteinCount),
                 #aes(color = ProteinCount, alpha = ProteinCount),
                 #arrow = arrow(length = unit(0.05, "inches")),
                 #edge_width = 2,
                 linejoin = "round", 
                 lineend = "round",
                 ) +
  scale_edge_width_continuous(range = c(1, 3)) +
  #scale_alpha_continuous(range = c(0.2,1)) +
  #xlim(-5, 5) +
  #ylim(-5, 5) +
  theme_void() +
  theme(legend.position="none") +
  #scale_edge_colour_gradient(low = "#132B43", high = "#56B1F7") +
  scale_edge_colour_viridis(direction = -1, begin = 0, end = 1, option = "rocket")
p
```

```{r}
p %>% ggsave("figures/petase_22n_dbg_7mers.png", ., device = "png", 
                         width = 12, height = 8, units = "in")
p %>% ggsave("figures/petase_22n_dbg_7mers.pdf", ., device = "pdf", 
                       width = 12, height = 8, units = "in")
```
